# Generated by Django 3.0.3 on 2020-03-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
