# Generated by Django 3.0.3 on 2020-03-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_pic_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='filename',
        ),
    ]
